Upgrade and downgrade aws2 to 2.21.6.
More recent versions will depends will use a version of aws-query-protocol which no longer have software.amazon.awssdk.protocols.query.interceptor.QueryParametersToBodyInterceptor which cause a java.lang.NoClassDefFoundError: software/amazon/awssdk/protocols/query/interceptor/QueryParametersToBodyInterceptor